### ISSUE TITLE
Email confirmation of registration

### ISSUE THREAD

**Issue by emilhem** [civictechsweden/civictech.se#1]
When I signed up for the Hackathon nr 2 I didn't receive any kind of confirmation message, neither via the website nor via email. Is this intended?

Maybe my input data was too long but then the error is instead that the website didn't warn me beforehand.

**Comment by p-jo** [comment]
Hi @emilhem ! Yes, unfortunately haven't been able to get email confirmations to work with the form platform that we are using (http://getsimpleform.com) for this static website. So you will get a manual confirmation instead :) See you at the hackathon!
