### ISSUE TITLE
Suggestion: enable RSS feeds

### ISSUE THREAD

**Issue by solarchemist** [civictechsweden/civictech.se#4]
Would it be possible to enable RSS feeds for events and posts? The point is to make it easier for people to keep track of news and coming events.

As far as I can tell, this is a Jekyll site. So technically speaking, it should be possible.

**Comment by PierreMesure** [comment]
Hi @chepec!

Thanks a lot for the suggestion! I agree with you!

I found this Jekyll plugin: [jekyll/jekyll-feed](https://github.com/jekyll/jekyll-feed) that does just that.

I don't have too much time to do it at the moment but will try in the coming months.

If you feel like it, don't hesitate to try and submit a PR! That might speed things up!
